Repository brazil-data-cube/wtss.py, pull requests merged in 2022-08, with the labels that each got.

#82 :heavy_check_mark: GeoJSON geometry tests #81 + restrict coverages to cubes
  examples/WTSS_jupyter_notebook.ipynb
  tests/conftest.py
  tests/test_wtss.py
  wtss/summarize.py
  wtss/timeseries.py
  wtss/wtss.py
Labels: enhancement

#85 :sparkles: Add plot quantile first/third (close #84)
  wtss/timeseries.py
Labels: enhancement

#87 :art: Minor changes in client 2.0 - review example and exception handling
  docs/sphinx/examples.rst
  examples/ts.py
  wtss/coverage.py
  wtss/summarize.py
  wtss/templates/coverage.html
  wtss/timeseries.py
  wtss/wtss.py
Labels: bug, enhancement

#88 :bug: Fix limit none comparison
  wtss/timeseries.py
Labels: bug
